### ISSUE TITLE
Indexes should be created at startup

### ISSUE THREAD

**Issue by dmaier-redislabs** [redislabs-training/keybase#3]
Hi Mirko,

Keybase should check if the indexes are already there and then load them. I guess this can be done during the startup of the Flask application.

Regards,
David

**Comment by mortensi** [comment]
Done, now at startup a check is made using `FT._LIST`. If indexes are not created, the routine in `application.py` creates the corresponding indexes (currently using 4).

```
127.0.0.1:6379> FT._LIST
1) "feedback_idx"
2) "vss_idx"
3) "user_idx"
4) "document_idx"
```
